[project]
name = "azure-auth-pgbouncer"
version = "0.1.1"
description = ""
authors = [
    {name = "Maciej Małecki",email = "me@mmalecki.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-identity (>=1.21.0,<2.0.0)",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
